ensembl_search_survey/urls.py
"""ensembl_search_survey URL Configuration

"""
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from main import views
urlpatterns = [
    path("", views.get_main, name="main"),
    path("survey/", include("survey.urls", namespace="survey")),
    path("search/", include("search.urls", namespace="search")),

]

urlpatterns += staticfiles_urlpatterns()
if settings.ADMIN_ENABLED:
    urlpatterns += [path('admin/', admin.site.urls), ]

search/urls.py
from django.urls import path

from . import views

app_name = "search"

urlpatterns = [
    path("", views.search, name="search"),
    path("results/", views.results, name="results"),
    path("results/feedback", views.update, name="feedback"),
]

survey/urls.py
from django.urls import path

from . import views

app_name = "survey"
urlpatterns = [
    path("", views.get_survey, name="survey"),
    path("save/", views.save, name="save"),
    path("thankyou", views.email_handler, name="thankyou"),
    path("done", views.done, name="done"),
]

survey/models.py
import uuid

from django.db import models
from django.conf import settings
from django_countries.fields import CountryField

SURVEY_CHOICES = list(enumerate(settings.SURVEY_CHOICES))
SURVEY_QUESTION = settings.SURVEY_QUESTION

JOB_CHOICES = (
    (1, "Academic institute/university"),
    (2, "Hospital or medical center"),
    (3, "Commercial"),
    (3, "Government"),
    (4, "Other"),
)
RATE_OF_USAGE_CHOICES = (
    (1, "Daily"),
    (2, "Weekly"),
    (3, "Monthly"),
    (4, "A couple of times a year or less"),
    (5, "Never"),
)


class Survey(models.Model):
    form_id = models.UUIDField(
        default=uuid.uuid4, unique=True
    )
    add_date = models.DateTimeField(auto_now_add=True)
    survey_question = models.CharField(max_length=255)
    survey_answer = models.CharField(max_length=255)
    result = models.JSONField(default={})
    keyword = models.CharField(max_length=255, blank=False)
    user = models.ForeignKey("UserDetails", on_delete=models.CASCADE)


class UserDetails(models.Model):
    add_date = models.DateTimeField(auto_now_add=True)
    country = CountryField(blank_label='(select country)')
    user_agent = models.CharField(blank=True, default='', max_length=300)
    email = models.EmailField(blank=True)
    uuid = models.UUIDField(
        db_index=True, default=uuid.uuid4, unique=True, primary_key=True
    )
    job = models.SmallIntegerField(
        choices=JOB_CHOICES, verbose_name="What kind of organisation do you work for?"
    )
    rate_of_usage = models.SmallIntegerField(
        choices=RATE_OF_USAGE_CHOICES,
        verbose_name="How often do you use Ensembl?",
        blank=True,
    )
    is_usage_gene_info = models.BooleanField(
        default=False, verbose_name="Gene information"
    )
    is_usage_genetic_variation = models.BooleanField(
        default=False, verbose_name="Genetic Variation"
    )
    is_usage_homology = models.BooleanField(
        default=False, verbose_name="Homology between species"
    )
    is_usage_functional_genomic_elements = models.BooleanField(
        default=False,
        verbose_name="Functional genomic elements that regulate expression",
    )
    is_usage_sequences = models.BooleanField(default=False, verbose_name="Sequences")

survey/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from django_countries.widgets import CountrySelectWidget

from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404

from .models import (
    UserDetails,
    JOB_CHOICES,
    SURVEY_CHOICES,
    Survey,
    RATE_OF_USAGE_CHOICES,
)


class UserDetailsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserDetailsForm, self).__init__(*args, **kwargs)
        self.fields["job"].label = ""
        self.fields["job"].required = True
        self.fields["rate_of_usage"].label = ""
        self.fields["rate_of_usage"].required = True
        self.fields["country"].label = ""
        self.helper = FormHelper()
        self.helper.render_required_fields = True

    job = forms.ChoiceField(choices=JOB_CHOICES, widget=forms.RadioSelect)
    rate_of_usage = forms.ChoiceField(
        choices=RATE_OF_USAGE_CHOICES, widget=forms.RadioSelect
    )

    class Meta:
        model = UserDetails
        fields = [
            "job",
            "country",
            "user_agent",
            "rate_of_usage",
            "is_usage_gene_info",
            "is_usage_genetic_variation",
            "is_usage_homology",
            "is_usage_functional_genomic_elements",
            "is_usage_sequences",
        ]

        widgets = {"job": forms.RadioSelect(), "rate_of_usage": forms.RadioSelect()}


class SurveySearchForm(forms.Form):
    survey_answer = forms.ChoiceField(choices=SURVEY_CHOICES, widget=forms.RadioSelect)

    def __init__(self, *args, **kwargs):
        if "uuid" in kwargs:
            self.uuid = kwargs.pop("uuid")
        super(SurveySearchForm, self).__init__(*args, **kwargs)
        self.fields["survey_answer"].label = ""

    def clean(self):
        """
        clean() is called by form.is_valid()
        Checking if the survey_id exists and matches the request's user
        """
        survey_object = get_object_or_404(Survey, form_id=self.data["survey_id"])
        if str(survey_object.user.uuid) != self.uuid:
            raise ValidationError("Invalid uuid")


class SurveyEmailForm(forms.Form):
    email = forms.EmailField()

survey/views.py
from django.shortcuts import render, redirect

from survey.forms import SurveyEmailForm
from .forms import UserDetailsForm
from .models import UserDetails


def get_survey(request):
    if request.session.get("user_session_id", False):
        return redirect(to="/search")

    validation = bool(request.GET.get("validation_error", False))
    form = UserDetailsForm()
    context = {"form": form, "error": validation}
    return render(request, "survey/index.html", context)


def save(request):
    try:
        data = request.POST.copy()
        data['user_agent'] = request.META['HTTP_USER_AGENT']
        form = UserDetailsForm(data=data)

        if form.is_valid():
            user_details = form.save()
            request.session["user_session_id"] = str(user_details.uuid)
            return redirect(to="/search")
        else:
            return redirect(to="/survey?validation_error=True")
    except Exception as e:
        print(e)


def email_handler(request):
    data = request.POST

    session_id = request.session.get("user_session_id", False)
    try:
        user = UserDetails.objects.get(uuid=session_id)
    except:
        return redirect(to="survey:survey")
    if user.email:
        return redirect(to="survey:done")
    form = SurveyEmailForm(data=data)
    if form.is_valid():
        user.email = form.cleaned_data["email"]
        user.save()
        return redirect(to="survey:done")
    else:
        return render(request, "survey/submit_email.html", context={"form": form})


def done(request):
    return render(request, "survey/thankyou.html")

templates/survey/index.html
{% extends "base.html" %}
{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <div class="row">
        Hello and thanks for helping out!<br><br>
    </div>
     <div class="row">
         The web team are considering redesigning <b style="display: contents;"> search </b> for the genetic data in Ensembl.<br><br>
     </div>
    <div class="row">

        This initial survey will help us find out
        </div>
       <div class="row">
          <ul>
            <li>how you search </li>
            <li>what you search for </li>
            <li>some preliminary information about the gene data you expect from your search results.</li>
          </ul><br><br>
    </div>
     <div class="row">
        Your answers will be combined with anonymised data about country, browser type, date and time and will help us to design a great search function for all users of Ensembl.<br><br>
     </div>
    <form action="{% url 'survey:save' %}" method="post">
        {% csrf_token %}
        {% if error %}
        <br>
        <div class="row">
            <div class="alert alert-danger col" role="alert">Please answer the questions specified with *.</div>
        </div>
        {% endif %}
        <br>
        <div class="row"><b>About you</b></div>
        <div class="row">
        <div class="col">
            <br>
             <label>What kind of organisation do you work for?*</label>
            {{form.job|as_crispy_field}}
            <br>
            <label>Where is your organisation?*</label>
            {{form.country|as_crispy_field}}
        </div>
        <div class="col">

        </div>
        <div class="col">
            <br><label>What data types are you interested in?</label>

                {{form.is_usage_gene_info|as_crispy_field}}

                {{form.is_usage_genetic_variation|as_crispy_field}}

                {{form.is_usage_homology|as_crispy_field}}

                {{form.is_usage_functional_genomic_elements|as_crispy_field}}

                {{form.is_usage_sequences|as_crispy_field}}

                        <br>
             <label>How often do you use Ensembl?*</label>
            {{form.rate_of_usage|as_crispy_field}}
            <br>
        </div>
        </div>



        <div class="row justify-content-end">
            <div class="col"> </div>
            <div class="col align-self-end">
            <input class="btn btn-success" type="submit" value="Next">
            </div>
        </div>
    </form>

</div>
{% endblock content %}

templates/survey/submit_email.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <div class="row">
        All done  - all your answers have been saved.<br><br>
    </div>
    <div class="row">
        <strong>Thank you for taking part in this survey. Your feedback is highly appreciated!<br><br><br></strong>
    </div>
    <div class="row">
        If you are happy to take part in another survey or for a member of Ensembl staff to contact you about the answers you have given, please enter your email address in the box below.<br><br><br>
    </div>


        <form action="{% url 'survey:thankyou' %}" method="post">
            {% csrf_token %}
            <div class="row h-100 justify-content-left align-items-left">
                <div class="col-2">
                <label for="email">Enter your email:</label>
                </div>
                <div class="col-3">
                <input type="email" class="form-control" id="email" name="email">
                </div>
                <div class="col">
                <input type="submit" class="btn btn-success" name="another_btn" value="Go"><br><br><br>
                </div>
            </div>
        </form>

    <div class="row">Thanks.<br><br><br></div>
    <div class="row">
        Check out <a style="padding-left: 4px;padding-right: 4px;" href="https://www.ensembl.org/index.html"> Ensembl </a>  and   <a  style="padding-left: 4px;padding-right: 4px;" href="https://ensemblgenomes.org/"> Ensembl genomes. </a>
    </div>
</div>
{% endblock content %}

templates/survey/thankyou.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <div class="row">
        All done  - all your answers have been saved.<br><br>
    </div>
    <div class="row">
        <strong>Thank you for taking part in this survey. Your feedback is highly appreciated!<br><br><br></strong>
    </div>
    <div class="row">
        If you are happy to take part in another survey or for a member of Ensembl staff to contact you about the answers you have given, please enter your email address in the box below.<br><br><br>
    </div>
        <div class="row">
        <div class="col">
Your email address has been successfully saved<br><br><br>
        </div>
    </div>
    <div class="row">Thanks.<br><br><br></div>
    <div class="row">
        Check out <a style="padding-left: 4px;padding-right: 4px;" href="https://www.ensembl.org/index.html"> Ensembl </a>  and   <a  style="padding-left: 4px;padding-right: 4px;" href="https://ensemblgenomes.org/"> Ensembl genomes. </a>
    </div>
</div>
{% endblock content %}