ensembl_search_survey/urls.py
"""ensembl_search_survey URL Configuration

"""
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from main import views
urlpatterns = [
    path("", views.get_main, name="main"),
    path("survey/", include("survey.urls", namespace="survey")),
    path("search/", include("search.urls", namespace="search")),

]

urlpatterns += staticfiles_urlpatterns()
if settings.ADMIN_ENABLED:
    urlpatterns += [path('admin/', admin.site.urls), ]

search/urls.py
from django.urls import path

from . import views

app_name = "search"

urlpatterns = [
    path("", views.search, name="search"),
    path("results/", views.results, name="results"),
    path("results/feedback", views.update, name="feedback"),
]

survey/urls.py
from django.urls import path

from . import views

app_name = "survey"
urlpatterns = [
    path("", views.get_survey, name="survey"),
    path("save/", views.save, name="save"),
    path("thankyou", views.email_handler, name="thankyou"),
    path("done", views.done, name="done"),
]

search/models.py
import json


class SearchResult:
    def __init__(self, total_hits, top_ten_results):
        self.total_hits = total_hits
        self.top_ten_results = top_ten_results

    def toJSON(self):
        data = {"total_hits": self.total_hits, "top_ten_results": self.top_ten_results}
        return json.dumps(data)

search/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponseForbidden, HttpResponse
from django.utils.html import escape

from survey.forms import SurveySearchForm
from survey.models import Survey, UserDetails, SURVEY_QUESTION, SURVEY_CHOICES
from search.service import EBISearchService



def search(request):
    if not request.session.get("user_session_id", False):
        return redirect(to="/survey")

    return render(request, "search/search.html")


def results(request):
    session_id = request.session.get("user_session_id", False)
    if not session_id:
        return redirect(to="/survey")

    search_term = request.GET.get("keyword")
    if search_term:
        search_service = EBISearchService(search_term)
        search_result = search_service.parse_result()
        survey = Survey(
            user=UserDetails.objects.get(uuid=session_id),
            keyword=search_term,
            result=search_result.toJSON(),
            survey_question=SURVEY_QUESTION,
        )
        survey.save()

        return render(
            request,
            "search/results.html",
            {
                "keyword": search_term,
                "result": search_result,
                "form": SurveySearchForm(),
                "survey_id": survey.form_id,
                "survey_question": SURVEY_QUESTION,
            },
        )


def update(request):
    data = request.POST

    try:
        session_id = request.session.get("user_session_id", False)
        form = SurveySearchForm(data=data, uuid=session_id)

        if form.is_valid():
            survey_object = Survey.objects.get(form_id=data["survey_id"])
            survey_answer_id = int(form.cleaned_data.get("survey_answer"))
            survey_object.survey_answer = dict(SURVEY_CHOICES)[survey_answer_id]
            survey_text = data.get("survey_text", None)
            if survey_text is not None:
                survey_object.survey_answer += " ### " + escape(survey_text.strip())
            survey_object.save()
            return HttpResponse(status=200)
        else:
            return HttpResponseForbidden("No permission")

    except Exception as e:
        print("=========", e)

templates/search/results.html
{% extends "base.html" %}
{% block content %}

{% load crispy_forms_tags %}
{% load static %}
<div class="container">
    <div class="row">For this initial survey we are only asking you to assess gene results.
    </div>
    <br>
    <div class="row">The top ten gene results of your search are shown below.
    </div>
    <div class="row search-line">You searched for:
        <span class="search-keyword">{{ keyword }}</span>
    </div>
    <div class="row results_label">
        <b>Results:</b>
        {% if result.total_hits == 0 %}
            <span class="total_count">0 results</span>
        {% endif %}
        {% if result.total_hits > 0 and result.total_hits < 10 %}
            <span class="total_count">Showing {{ result.total_hits }} of {{ result.total_hits }} results</span>
        {% endif %}
        {% if result.total_hits >= 10 %}
            <span class="total_count">Showing 10 of {{ result.total_hits }} results</span>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-8 results_list">
        {% if result.total_hits >= 0 %}
            {% for item in result.top_ten_results %}
                {% if item.name %}
                <div class="row"><b>Gene symbol: &nbsp;</b> {{ item.name }}</div>
                {% endif %}
                {% if item.domain_source %}
                <div class="row"><b>Type: &nbsp;</b> gene </div>
                {% endif %}
                {% if item.system_name %}
                <div class="row"><b>Species: &nbsp;</b> {{ item.system_name }} </div>
                {% endif %}
                {% if item.id %}
                <div class="row"><b>Gene ID: &nbsp;</b> {{ item.id }}</div>
                {% endif %}
                {% if item.description %}
                <div class="row"><b>Description: &nbsp;</b> {{ item.description }} </div>
                {% endif %}
                <br>
            {% endfor %}
        {% else %}
            <div class="warning">
            API ERROR: {{ result.top_ten_results.err }}
            </div>
        {% endif %}
        </div>
        <div class="col">
            <form id="feedback_form" ajaxAction="{% url 'search:feedback' %}" onsubmit="return false">
                {% csrf_token %}
                <label> {{ survey_question}} </label>
                <div>They are</div>
                    {{ form.survey_answer|as_crispy_field }}
                <input type="hidden" id="survey_id" value="{{ survey_id }}">
                <br>
                <textarea placeholder="Please let us know what information you needed that was missing from the gene results for your search?" class="survey_text_box block_hidden"></textarea>
                <div id="survey_answer_warning" class="block_hidden">
                    <p class="warning"><i>You need to select one option</i></p>
                </div>
                <input type="submit" class="btn btn-success" id="main_submit_btn" value="Submit">
            </form>
            <div id="after_submit_btns" class="block_hidden">
                <p><b>Answer submitted</b></p>
                <div class="another-search-text">
                    How about trying another search? <br>
                    Please try as many searches as you can - as we said the more the better! Thanks
                </div>
                <a href="{% url 'survey:survey' %}" >
                    <input type="button" class="btn btn-success btn-result-page" value="Try a new search">
                </a>
                <a href="{% url 'survey:thankyou' %}" >
                    <input type="button" class="btn btn-success btn-result-page btn-next" value="End of survey">
                </a>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/result-page.js' %}"></script>
{% endblock content %}

templates/search/search.html
{% extends "base.html" %}
{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <div class="row">
        Imagine you’re searching a new genomics service for all genetic data types.<br><br>
    </div>
    <div class="row">
        <strong>Search</strong><br><br>
    </div>
    <div class="row">
        We would like you to run as many searches as you have time for (ideally 4-5) and make a quick assessment of the results provided.<br><br>
    </div>
    <div class="row">
        We will also ask you to make a quick assessment of the gene results provided. <br><br>
    </div>

    <div class="row">
        For this initial survey we are only asking you to assess gene results ie only gene results will be provided. <br><br>
    </div>
    <div class="row">
        <strong>Results</strong><br><br>
    </div>
    <div class="row">
        We will assess the results of other data types ie variants, orthologues, regulatory elements, iteratively in future tests and surveys. <br><br>
    </div>

    <div class="row">
        We would still like you to search as if any data type could be returned by your search. <br><br>
    </div>
    <div class="row">
        This section is the main part of the survey<br><br>
    </div>
    <div class="row">
        <b>Please try any search term in the box below:</b>
        <br>
        <br>
    </div>
    <form action="{% url 'search:results' %}" method="get" target="_top">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-1"><strong>Find</strong></div>
            <div class="col-10">

            <input class="form-control" type="text" placeholder="Type here" name="keyword" required>

            </div>

            <div class="col-1">
                <input class="btn btn-success" type="submit" value="Go">
            </div>
        </div>
    </form>
</div>

{% endblock content %}